# **Ensamble Classifiers**

**NB** : Carica il dataset df2 senza lo standard Scaler fatto per il SVM

## **Data Preparation**

In [1]:
%matplotlib inline
import math
import numpy as np
import pandas as pd
import scipy.stats as stats
from sklearn import preprocessing
import matplotlib.pyplot as plt
import seaborn as sns

from collections import defaultdict
from scipy.stats.stats import pearsonr

In [2]:
df = pd.read_csv('AirQualityUCI.csv', sep=';',decimal=",") 

In [3]:
df.head()

Date      Time  CO(GT)  ...      AH  Unnamed: 15  Unnamed: 16
0  10/03/2004  18.00.00     2.6  ...  0.7578          NaN          NaN
1  10/03/2004  19.00.00     2.0  ...  0.7255          NaN          NaN
2  10/03/2004  20.00.00     2.2  ...  0.7502          NaN          NaN
3  10/03/2004  21.00.00     2.2  ...  0.7867          NaN          NaN
4  10/03/2004  22.00.00     1.6  ...  0.7888          NaN          NaN

[5 rows x 17 columns]

In [4]:
df.tail()

Date Time  CO(GT)  PT08.S1(CO)  ...  RH  AH  Unnamed: 15  Unnamed: 16
9466  NaN  NaN     NaN          NaN  ... NaN NaN          NaN          NaN
9467  NaN  NaN     NaN          NaN  ... NaN NaN          NaN          NaN
9468  NaN  NaN     NaN          NaN  ... NaN NaN          NaN          NaN
9469  NaN  NaN     NaN          NaN  ... NaN NaN          NaN          NaN
9470  NaN  NaN     NaN          NaN  ... NaN NaN          NaN          NaN

[5 rows x 17 columns]

In [5]:
df.dtypes

Date              object
Time              object
CO(GT)           float64
PT08.S1(CO)      float64
NMHC(GT)         float64
C6H6(GT)         float64
PT08.S2(NMHC)    float64
NOx(GT)          float64
PT08.S3(NOx)     float64
NO2(GT)          float64
PT08.S4(NO2)     float64
PT08.S5(O3)      float64
T                float64
RH               float64
AH               float64
Unnamed: 15      float64
Unnamed: 16      float64
dtype: object

In [6]:
df.describe()

CO(GT)  PT08.S1(CO)  ...  Unnamed: 15  Unnamed: 16
count  9357.000000  9357.000000  ...          0.0          0.0
mean    -34.207524  1048.990061  ...          NaN          NaN
std      77.657170   329.832710  ...          NaN          NaN
min    -200.000000  -200.000000  ...          NaN          NaN
25%       0.600000   921.000000  ...          NaN          NaN
50%       1.500000  1053.000000  ...          NaN          NaN
75%       2.600000  1221.000000  ...          NaN          NaN
max      11.900000  2040.000000  ...          NaN          NaN

[8 rows x 15 columns]

##### Drop Columns Unnamed

First of all we saw that there are 2 columns that contain only NaN values, so we dropped out that columns.

The columns are labeled as Unnamed: 15 and Unnamed: 16

In [7]:
df = df.drop(["Unnamed: 15","Unnamed: 16"], axis=1)

In [8]:
df.head()

Date      Time  CO(GT)  PT08.S1(CO)  ...  PT08.S5(O3)     T    RH      AH
0  10/03/2004  18.00.00     2.6       1360.0  ...       1268.0  13.6  48.9  0.7578
1  10/03/2004  19.00.00     2.0       1292.0  ...        972.0  13.3  47.7  0.7255
2  10/03/2004  20.00.00     2.2       1402.0  ...       1074.0  11.9  54.0  0.7502
3  10/03/2004  21.00.00     2.2       1376.0  ...       1203.0  11.0  60.0  0.7867
4  10/03/2004  22.00.00     1.6       1272.0  ...       1110.0  11.2  59.6  0.7888

[5 rows x 15 columns]

##### Drop column NMHC(GT)

In this column there are too much -200 values (missing values) so also if we replace with mean of the feature is too much dependent from this missing values.

In [9]:
df = df.drop(["NMHC(GT)"], axis=1)

##### NaN Values

Drop columns with NaN, the last 2, Unnamed:15 and Unnamed:16
Drop rows with NaN , there only 1% circa.


In [10]:
df.isnull().any()

Date             True
Time             True
CO(GT)           True
PT08.S1(CO)      True
C6H6(GT)         True
PT08.S2(NMHC)    True
NOx(GT)          True
PT08.S3(NOx)     True
NO2(GT)          True
PT08.S4(NO2)     True
PT08.S5(O3)      True
T                True
RH               True
AH               True
dtype: bool

In [11]:
df.isnull().sum()

Date             114
Time             114
CO(GT)           114
PT08.S1(CO)      114
C6H6(GT)         114
PT08.S2(NMHC)    114
NOx(GT)          114
PT08.S3(NOx)     114
NO2(GT)          114
PT08.S4(NO2)     114
PT08.S5(O3)      114
T                114
RH               114
AH               114
dtype: int64

In [12]:
df.shape

(9471, 14)

In [13]:
df

Date      Time  CO(GT)  ...     T    RH      AH
0     10/03/2004  18.00.00     2.6  ...  13.6  48.9  0.7578
1     10/03/2004  19.00.00     2.0  ...  13.3  47.7  0.7255
2     10/03/2004  20.00.00     2.2  ...  11.9  54.0  0.7502
3     10/03/2004  21.00.00     2.2  ...  11.0  60.0  0.7867
4     10/03/2004  22.00.00     1.6  ...  11.2  59.6  0.7888
...          ...       ...     ...  ...   ...   ...     ...
9466         NaN       NaN     NaN  ...   NaN   NaN     NaN
9467         NaN       NaN     NaN  ...   NaN   NaN     NaN
9468         NaN       NaN     NaN  ...   NaN   NaN     NaN
9469         NaN       NaN     NaN  ...   NaN   NaN     NaN
9470         NaN       NaN     NaN  ...   NaN   NaN     NaN

[9471 rows x 14 columns]

In [14]:
df= df.dropna()

In [15]:
df.shape

(9357, 14)

In [16]:
df

Date      Time  CO(GT)  ...     T    RH      AH
0     10/03/2004  18.00.00     2.6  ...  13.6  48.9  0.7578
1     10/03/2004  19.00.00     2.0  ...  13.3  47.7  0.7255
2     10/03/2004  20.00.00     2.2  ...  11.9  54.0  0.7502
3     10/03/2004  21.00.00     2.2  ...  11.0  60.0  0.7867
4     10/03/2004  22.00.00     1.6  ...  11.2  59.6  0.7888
...          ...       ...     ...  ...   ...   ...     ...
9352  04/04/2005  10.00.00     3.1  ...  21.9  29.3  0.7568
9353  04/04/2005  11.00.00     2.4  ...  24.3  23.7  0.7119
9354  04/04/2005  12.00.00     2.4  ...  26.9  18.3  0.6406
9355  04/04/2005  13.00.00     2.1  ...  28.3  13.5  0.5139
9356  04/04/2005  14.00.00     2.2  ...  28.5  13.1  0.5028

[9357 rows x 14 columns]

After the drop of NaN values in rows we have passed from 9471 rows to 9357 rows.


In [17]:
df.dtypes

Date              object
Time              object
CO(GT)           float64
PT08.S1(CO)      float64
C6H6(GT)         float64
PT08.S2(NMHC)    float64
NOx(GT)          float64
PT08.S3(NOx)     float64
NO2(GT)          float64
PT08.S4(NO2)     float64
PT08.S5(O3)      float64
T                float64
RH               float64
AH               float64
dtype: object

##### Missing values with "-200" value

In [18]:
df.isin([-200.0]).any()

Date             False
Time             False
CO(GT)            True
PT08.S1(CO)       True
C6H6(GT)          True
PT08.S2(NMHC)     True
NOx(GT)           True
PT08.S3(NOx)      True
NO2(GT)           True
PT08.S4(NO2)      True
PT08.S5(O3)       True
T                 True
RH                True
AH                True
dtype: bool

We know if there is a value with -200 is a missing value by the discription of the dataset, so, we want replace this values with the mean of the each column

In [19]:
df1=df.replace(-200.0, np.nan)

In [20]:
df1.isin([-200]).any()

Date             False
Time             False
CO(GT)           False
PT08.S1(CO)      False
C6H6(GT)         False
PT08.S2(NMHC)    False
NOx(GT)          False
PT08.S3(NOx)     False
NO2(GT)          False
PT08.S4(NO2)     False
PT08.S5(O3)      False
T                False
RH               False
AH               False
dtype: bool

In [21]:
df1.isnull().any()

Date             False
Time             False
CO(GT)            True
PT08.S1(CO)       True
C6H6(GT)          True
PT08.S2(NMHC)     True
NOx(GT)           True
PT08.S3(NOx)      True
NO2(GT)           True
PT08.S4(NO2)      True
PT08.S5(O3)       True
T                 True
RH                True
AH                True
dtype: bool

In [22]:
dataframe= df1.fillna(df1.mean())

In [23]:
dataframe.isnull().any()

Date             False
Time             False
CO(GT)           False
PT08.S1(CO)      False
C6H6(GT)         False
PT08.S2(NMHC)    False
NOx(GT)          False
PT08.S3(NOx)     False
NO2(GT)          False
PT08.S4(NO2)     False
PT08.S5(O3)      False
T                False
RH               False
AH               False
dtype: bool

In [24]:
dataframe

Date      Time  CO(GT)  ...     T    RH      AH
0     10/03/2004  18.00.00     2.6  ...  13.6  48.9  0.7578
1     10/03/2004  19.00.00     2.0  ...  13.3  47.7  0.7255
2     10/03/2004  20.00.00     2.2  ...  11.9  54.0  0.7502
3     10/03/2004  21.00.00     2.2  ...  11.0  60.0  0.7867
4     10/03/2004  22.00.00     1.6  ...  11.2  59.6  0.7888
...          ...       ...     ...  ...   ...   ...     ...
9352  04/04/2005  10.00.00     3.1  ...  21.9  29.3  0.7568
9353  04/04/2005  11.00.00     2.4  ...  24.3  23.7  0.7119
9354  04/04/2005  12.00.00     2.4  ...  26.9  18.3  0.6406
9355  04/04/2005  13.00.00     2.1  ...  28.3  13.5  0.5139
9356  04/04/2005  14.00.00     2.2  ...  28.5  13.1  0.5028

[9357 rows x 14 columns]

Now our dataset is called dataframe, we dropped out NaN columns and NMHC(GT) column, we dropped NaN values and we replaced the -200 missing values with the mean of the column.

##### Deal with Data and Time

In this section we are going to deal with Date and Time format

###### Date

The problem is that i need the format year - month - day to use datetime function, so i have to switch month with day 

In [25]:
dataframe['Date']=pd.to_datetime(dataframe.Date, dayfirst=True)

In [26]:
dataframe['Weekday']=dataframe.Date.dt.weekday

In [27]:
dataframe['Month']=dataframe.Date.dt.month

In [28]:
dataframe.dtypes


Date             datetime64[ns]
Time                     object
CO(GT)                  float64
PT08.S1(CO)             float64
C6H6(GT)                float64
PT08.S2(NMHC)           float64
NOx(GT)                 float64
PT08.S3(NOx)            float64
NO2(GT)                 float64
PT08.S4(NO2)            float64
PT08.S5(O3)             float64
T                       float64
RH                      float64
AH                      float64
Weekday                   int64
Month                     int64
dtype: object

In [29]:
dataframe

Date      Time  CO(GT)  PT08.S1(CO)  ...    RH      AH  Weekday  Month
0    2004-03-10  18.00.00     2.6       1360.0  ...  48.9  0.7578        2      3
1    2004-03-10  19.00.00     2.0       1292.0  ...  47.7  0.7255        2      3
2    2004-03-10  20.00.00     2.2       1402.0  ...  54.0  0.7502        2      3
3    2004-03-10  21.00.00     2.2       1376.0  ...  60.0  0.7867        2      3
4    2004-03-10  22.00.00     1.6       1272.0  ...  59.6  0.7888        2      3
...         ...       ...     ...          ...  ...   ...     ...      ...    ...
9352 2005-04-04  10.00.00     3.1       1314.0  ...  29.3  0.7568        0      4
9353 2005-04-04  11.00.00     2.4       1163.0  ...  23.7  0.7119        0      4
9354 2005-04-04  12.00.00     2.4       1142.0  ...  18.3  0.6406        0      4
9355 2005-04-04  13.00.00     2.1       1003.0  ...  13.5  0.5139        0      4
9356 2005-04-04  14.00.00     2.2       1071.0  ...  13.1  0.5028        0      4

[9357 rows x 16 columns]

Now the Data Format it's ok and also i create a new feature Weekday with 0=monday and ..... and 6=Sunday.

###### Time

From Time feature i figure out only the hour and assign it to new feature Hour

In [30]:
dataframe['Hour'] = pd.to_datetime(dataframe['Time'],format= '%H.%M.%S').dt.hour
type(dataframe['Time'][0])

str

In [31]:
dataframe.dtypes

Date             datetime64[ns]
Time                     object
CO(GT)                  float64
PT08.S1(CO)             float64
C6H6(GT)                float64
PT08.S2(NMHC)           float64
NOx(GT)                 float64
PT08.S3(NOx)            float64
NO2(GT)                 float64
PT08.S4(NO2)            float64
PT08.S5(O3)             float64
T                       float64
RH                      float64
AH                      float64
Weekday                   int64
Month                     int64
Hour                      int64
dtype: object

In [32]:
dataframe

Date      Time  CO(GT)  PT08.S1(CO)  ...      AH  Weekday  Month  Hour
0    2004-03-10  18.00.00     2.6       1360.0  ...  0.7578        2      3    18
1    2004-03-10  19.00.00     2.0       1292.0  ...  0.7255        2      3    19
2    2004-03-10  20.00.00     2.2       1402.0  ...  0.7502        2      3    20
3    2004-03-10  21.00.00     2.2       1376.0  ...  0.7867        2      3    21
4    2004-03-10  22.00.00     1.6       1272.0  ...  0.7888        2      3    22
...         ...       ...     ...          ...  ...     ...      ...    ...   ...
9352 2005-04-04  10.00.00     3.1       1314.0  ...  0.7568        0      4    10
9353 2005-04-04  11.00.00     2.4       1163.0  ...  0.7119        0      4    11
9354 2005-04-04  12.00.00     2.4       1142.0  ...  0.6406        0      4    12
9355 2005-04-04  13.00.00     2.1       1003.0  ...  0.5139        0      4    13
9356 2005-04-04  14.00.00     2.2       1071.0  ...  0.5028        0      4    14

[9357 rows x 17 columns]

##### New features

At this point we want implement some new features, like 'is night' , 'is evening' , 'officheHour' and 'is weekend' .
Aftet that for each variable we transform from boolean to int 0 and 1 .
1 == True
0 == False

In [33]:
# dataframe['is Evening'] = (dataframe['Hour'] >= 18) 

In [34]:
# dataframe['is Evening'] = dataframe['is Evening'].astype(int)

In [35]:
# dataframe['is Night'] = ( (dataframe['Hour'] >= 18) | (dataframe['Hour'] <6) )

In [36]:
# dataframe['is Night'] = dataframe['is Night'].astype(int)

In [37]:
# dataframe['OfficeHour'] = ( (dataframe['Hour'] >= 9) & (dataframe['Hour'] <=18 ) )

In [38]:
# dataframe['OfficeHour'] = dataframe['OfficeHour'].astype(int)

In [39]:
dataframe['Weekend'] = ( (dataframe['Weekday'] == 5) | (dataframe['Weekday'] == 6) )

In [40]:
dataframe['Weekend'] = dataframe['Weekend'].astype(int)

In [41]:
dataframe

Date      Time  CO(GT)  PT08.S1(CO)  ...  Weekday  Month  Hour  Weekend
0    2004-03-10  18.00.00     2.6       1360.0  ...        2      3    18        0
1    2004-03-10  19.00.00     2.0       1292.0  ...        2      3    19        0
2    2004-03-10  20.00.00     2.2       1402.0  ...        2      3    20        0
3    2004-03-10  21.00.00     2.2       1376.0  ...        2      3    21        0
4    2004-03-10  22.00.00     1.6       1272.0  ...        2      3    22        0
...         ...       ...     ...          ...  ...      ...    ...   ...      ...
9352 2005-04-04  10.00.00     3.1       1314.0  ...        0      4    10        0
9353 2005-04-04  11.00.00     2.4       1163.0  ...        0      4    11        0
9354 2005-04-04  12.00.00     2.4       1142.0  ...        0      4    12        0
9355 2005-04-04  13.00.00     2.1       1003.0  ...        0      4    13        0
9356 2005-04-04  14.00.00     2.2       1071.0  ...        0      4    14        0

[9357 rows x 18 columns]

In [42]:
dataframe.dtypes

Date             datetime64[ns]
Time                     object
CO(GT)                  float64
PT08.S1(CO)             float64
C6H6(GT)                float64
PT08.S2(NMHC)           float64
NOx(GT)                 float64
PT08.S3(NOx)            float64
NO2(GT)                 float64
PT08.S4(NO2)            float64
PT08.S5(O3)             float64
T                       float64
RH                      float64
AH                      float64
Weekday                   int64
Month                     int64
Hour                      int64
Weekend                   int64
dtype: object

In [43]:
dataframe['Weekend'].value_counts()

0    6669
1    2688
Name: Weekend, dtype: int64

Lavoreremo su un dataset che contiene solo i gas, la T, Rh e la varibiale dipendente Weekend

In [44]:
df2 = dataframe[["CO(GT)", "PT08.S1(CO)", "C6H6(GT)",	"PT08.S2(NMHC)", "NOx(GT)",	"PT08.S3(NOx)",	"NO2(GT)",	"PT08.S4(NO2)",	"PT08.S5(O3)","T"	,"RH"	,"Weekend"]]

In [45]:
df2.head()

CO(GT)  PT08.S1(CO)  C6H6(GT)  ...     T    RH  Weekend
0     2.6       1360.0      11.9  ...  13.6  48.9        0
1     2.0       1292.0       9.4  ...  13.3  47.7        0
2     2.2       1402.0       9.0  ...  11.9  54.0        0
3     2.2       1376.0       9.2  ...  11.0  60.0        0
4     1.6       1272.0       6.5  ...  11.2  59.6        0

[5 rows x 12 columns]

In [46]:
df2.head()

CO(GT)  PT08.S1(CO)  C6H6(GT)  ...     T    RH  Weekend
0     2.6       1360.0      11.9  ...  13.6  48.9        0
1     2.0       1292.0       9.4  ...  13.3  47.7        0
2     2.2       1402.0       9.0  ...  11.9  54.0        0
3     2.2       1376.0       9.2  ...  11.0  60.0        0
4     1.6       1272.0       6.5  ...  11.2  59.6        0

[5 rows x 12 columns]

In [47]:
from sklearn.model_selection import train_test_split

In [48]:
attributes = [col for col in df2.columns if col != 'Weekend']
X = df2[attributes].values
y = df2['Weekend']

In [49]:
X_train, X_test, y_train, y_test = train_test_split(X,y,test_size=0.20, random_state=10)

In [50]:
X_train.shape

(7485, 11)

In [51]:
y_train.shape

(7485,)

## **Random Forest**

A random forest is a meta estimator that fits a number of decision tree classifiers on various sub-samples of the dataset and uses averaging to improve the predictive accuracy and control over-fitting.

Random forest algorithm parameters:
- n_estimators: The number of trees in the forest.
- criterion: The function to measure the quality of a split. Supported criteria are "gini" for the Gini impurity and "entropy" for the information gain.
- max_depth: The maximum depth of the tree. If None, then nodes are expanded until all leaves are pure or until all leaves contain less than min_samples_split samples.
- min_samples_split: The minimum number of samples required to split an internal node.
- min_samples_leaf: The minimum number of samples required to be at a leaf node. A split point at any depth will only be considered if it leaves at least min_samples_leaf training samples in each of the left and right branches. This may have the effect of smoothing the model, especially in regression.
- min_weight_fraction_leaf: The minimum weighted fraction of the sum total of weights (of all the input samples) required to be at a leaf node. Samples have equal weight when sample_weight is not provided.
- max_features: The number of features to consider when looking for the best split.
- max_leaf_nodes: Grow a tree with max_leaf_nodes in best-first fashion. Best nodes are defined as relative reduction in impurity. If None then unlimited number of leaf nodes.
- min_impurity_decrease: A node will be split if this split induces a decrease of the impurity greater than or equal to this value.
- min_impurity_split: Threshold for early stopping in tree growth. A node will split if its impurity is above the threshold, otherwise it is a leaf.
- bootstrap: Whether bootstrap samples are used when building trees. If False, the whole datset is used to build each tree.
- oob_score: Whether to use out-of-bag samples to estimate the generalization accuracy.

Quelli sono tutti i parametri, i + "importanti" sono:

- max_depth: The maximum splits for all trees in the forest. bootstrap: An indicator of whether or not we want to use bootstrap samples when building trees.
- max_features: The maximum number of features that will be used in node splitting — the main difference I previously mentioned between bagging trees and random forest. Typically, you want a value that is less than p, where p is all features in your data set.
- criterion: This is the metric used to asses the stopping criteria for the decision trees.

In [52]:
from sklearn.ensemble import RandomForestClassifier

In [53]:
from sklearn.model_selection import train_test_split, cross_val_score 

from sklearn.metrics import accuracy_score, f1_score, classification_report
from sklearn.metrics import roc_curve, auc, roc_auc_score

In [54]:
attributes=["CO(GT)",	"PT08.S1(CO)",	"C6H6(GT)",	"PT08.S2(NMHC)",	"NOx(GT)",	"PT08.S3(NOx)",	"NO2(GT)",	"PT08.S4(NO2)","PT08.S5(O3)",	"T"	,"RH"] 

Vado a usare il GridSearch per stimare i migliori parametri del Random Forest.
Per farlo abbiamo preso un set di "validazione" di 5 e utilizzando come scoring l'accuracy.
I parametri presi in consideazione sono:
- n_estimators: 1, 2, 5, 10, 20, 30, 40, 50, 55, 100

- max_depth: 1, 4, 6, 8, 10 , che rappresenta massima ampiezza albero

- criterion:'gini', 'entropy' , che rappresentano le misure di impurità

- min_samples_split:2,4,5,10,20,50 , rappresenta il numero minimo di record richiesti per dividere un nodo interno 

- min_samples_leaf:1,2,4,5,10,20,35,50 , rappresenta il minimo numero di record richiesti in un nodo folgia

In [55]:
from sklearn.ensemble import RandomForestClassifier
from sklearn.model_selection import GridSearchCV

In [56]:
param_grid = {"n_estimators": [1, 2, 5, 10, 20, 30, 40, 50, 55, 100],
              "max_depth": [1, 4, 6, 8, 10],
              "criterion":['gini', 'entropy'],
              "min_samples_split":[2,4,5,10,20,50],
              "min_samples_leaf":[1,2,4,5,10,20,35,50]
             }

# run grid search
grid = GridSearchCV(RandomForestClassifier(), param_grid, cv = 5, scoring = 'accuracy')
grid.fit(X_train, y_train)

GridSearchCV(cv=5, error_score=nan,
             estimator=RandomForestClassifier(bootstrap=True, ccp_alpha=0.0,
                                              class_weight=None,
                                              criterion='gini', max_depth=None,
                                              max_features='auto',
                                              max_leaf_nodes=None,
                                              max_samples=None,
                                              min_impurity_decrease=0.0,
                                              min_impurity_split=None,
                                              min_samples_leaf=1,
                                              min_samples_split=2,
                                              min_weight_fraction_leaf=0.0,
                                              n_estimators=100, n_jobs=None,...
                                              random_state=None, verbose=0,
                                   

In [57]:
Randf = grid.best_estimator_
Randf

RandomForestClassifier(bootstrap=True, ccp_alpha=0.0, class_weight=None,
                       criterion='gini', max_depth=10, max_features='auto',
                       max_leaf_nodes=None, max_samples=None,
                       min_impurity_decrease=0.0, min_impurity_split=None,
                       min_samples_leaf=2, min_samples_split=4,
                       min_weight_fraction_leaf=0.0, n_estimators=100,
                       n_jobs=None, oob_score=False, random_state=None,
                       verbose=0, warm_start=False)

Secondo la GridSearch i migliori parametri per RandomForest sono bootstrap=True, ccp_alpha=0.0, class_weight=None, criterion='gini', max_depth=10, max_features='auto', max_leaf_nodes=None, max_samples=None,
min_impurity_decrease=0.0, min_impurity_split=None, min_samples_leaf=1, min_samples_split=2, min_weight_fraction_leaf=0.0, n_estimators=100, n_jobs=None, oob_score=False, random_state=None, verbose=0, warm_start=False

Questi sono tutti, in report metti quelli che hai evidenziato a inizio

In [58]:
Randf.fit(X_train, y_train)

y_pred = Randf.predict(X_test)

print('Accuracy %s' % accuracy_score(y_test, y_pred))
print('F1-score %s' % f1_score(y_test, y_pred, average=None))
print(classification_report(y_test, y_pred))

Accuracy 0.7783119658119658
F1-score [0.86097152 0.45322793]
              precision    recall  f1-score   support

           0       0.78      0.96      0.86      1332
           1       0.79      0.32      0.45       540

    accuracy                           0.78      1872
   macro avg       0.78      0.64      0.66      1872
weighted avg       0.78      0.78      0.74      1872



le performance del random Forest sono queste indicate sopra, in particolare abbiamo una valore di accuracy di 0.78

In [59]:
fpr, tpr, _ = roc_curve(y_test, y_pred)
roc_auc = auc(fpr, tpr)
print(roc_auc)

0.6416166166166166


Il valore di AUC è di 0.644


In [60]:
plt.figure(figsize=(8, 5))
plt.plot(fpr, tpr, label='ROC curve (area = %0.2f)' % (roc_auc), color='darkorange')
    
plt.plot([0, 1], [0, 1], 'k--',color='navy')
plt.xlim([0.0, 1.0])
plt.ylim([0.0, 1.05])
plt.xlabel('False Positive Rate', fontsize=20)
plt.ylabel('True Positive Rate', fontsize=20) 
plt.tick_params(axis='both', which='major', labelsize=22)
plt.legend(loc="lower right", fontsize=14, frameon=False)
plt.show()

In [61]:
import pydotplus
from sklearn import tree
from IPython.display import Image
from sklearn.tree import export_graphviz

In [62]:
dot_data = tree.export_graphviz(Randf.estimators_[0], out_file=None,  
                                feature_names=attributes, 
                                class_names=['Weekend' if x == 1 else 'NoWeekend' for x in Randf.classes_],  
                                filled=True, rounded=True,  
                                special_characters=True, max_depth=4)  
graph = pydotplus.graph_from_dot_data(dot_data)  
Image(graph.create_png())

In [63]:
nbr_features = 11

tree_feature_importances = Randf.feature_importances_
sorted_idx = tree_feature_importances.argsort()[-nbr_features:]

y_ticks = np.arange(0, len(sorted_idx))
fig, ax = plt.subplots()
plt.barh(y_ticks, tree_feature_importances[sorted_idx])
plt.yticks(y_ticks, np.array(attributes)[sorted_idx])
plt.title("Random Forest Feature Importances (MDI)")
plt.show()

Questo è bellino mettilo in report dice quali sono le features + importanti per il random forest

## **AdaBoost**

L’AdaBoost è un classificatore adottato in concomitanza con
altri algoritmi di classificazione. L’output di questi algoritmi
viene combinato mediante una somma pesata per ottenere
l’output finale. 
Nel nostro caso lo faremo su Random Forest Classifier

In [66]:
from sklearn.tree import DecisionTreeClassifier
from sklearn.ensemble import AdaBoostClassifier

In [67]:
param_grid = {"n_estimators": [1, 2, 5, 10, 20, 30, 40, 50, 55, 100],
              "learning_rate": [0.01, 0.05, 0.1, .5, 1.0],
              "algorithm":['SAMME.R', 'SAMME']
             }

# run grid search
grid = GridSearchCV(AdaBoostClassifier(RandomForestClassifier(bootstrap=True, ccp_alpha=0.0, class_weight=None,
                       criterion='gini', max_depth=8, max_features='auto',
                       max_leaf_nodes=None, max_samples=None,
                       min_impurity_decrease=0.0, min_impurity_split=None,
                       min_samples_leaf=2, min_samples_split=2,
                       min_weight_fraction_leaf=0.0, n_estimators=10,
                       n_jobs=None, oob_score=False, random_state=None,
                       verbose=0, warm_start=False)),cv = 5, param_grid=param_grid, scoring = 'accuracy')
grid.fit(X_train, y_train)

GridSearchCV(cv=5, error_score=nan,
             estimator=AdaBoostClassifier(algorithm='SAMME.R',
                                          base_estimator=RandomForestClassifier(bootstrap=True,
                                                                                ccp_alpha=0.0,
                                                                                class_weight=None,
                                                                                criterion='gini',
                                                                                max_depth=8,
                                                                                max_features='auto',
                                                                                max_leaf_nodes=None,
                                                                                max_samples=None,
                                                                                min_impurity_decrease=0.0,
             

In [68]:
Boost_rand= grid.best_estimator_
Boost_rand

AdaBoostClassifier(algorithm='SAMME.R',
                   base_estimator=RandomForestClassifier(bootstrap=True,
                                                         ccp_alpha=0.0,
                                                         class_weight=None,
                                                         criterion='gini',
                                                         max_depth=8,
                                                         max_features='auto',
                                                         max_leaf_nodes=None,
                                                         max_samples=None,
                                                         min_impurity_decrease=0.0,
                                                         min_impurity_split=None,
                                                         min_samples_leaf=2,
                                                         min_samples_split=2,
                                          

Questi sopra sono i parametri del miglior random forest con ADABoost usando la GridSearch, in report metti solo i principali che hai evidenziato a inizio.

In [69]:
Boost_rand.fit(X_train, y_train)

y_pred = Boost_rand.predict(X_test)

print('Accuracy %s' % accuracy_score(y_test, y_pred))
print('F1-score %s' % f1_score(y_test, y_pred, average=None))
print(classification_report(y_test, y_pred))

Accuracy 0.8210470085470085
F1-score [0.88082533 0.64094319]
              precision    recall  f1-score   support

           0       0.84      0.93      0.88      1332
           1       0.76      0.55      0.64       540

    accuracy                           0.82      1872
   macro avg       0.80      0.74      0.76      1872
weighted avg       0.82      0.82      0.81      1872



Risulati non brutti ma poteva andare meglio

In [70]:
color0 = '#FD4F0F'
color1 = '#15B985'

In [71]:
from sklearn.datasets import make_gaussian_quantiles

# Create and fit an AdaBoosted decision tree
X = df2[['CO(GT)','NOx(GT)']].values
y = df2['Weekend']

Boost_rand.fit(X, y)

plot_colors = (color0,color1)
plot_step = 0.02
class_names = "01"

plt.figure(figsize=(10, 5))

# Plot the decision boundaries
plt.subplot(121)
x_min, x_max = X[:, 0].min() - 1, X[:, 0].max() + 1
y_min, y_max = X[:, 1].min() - 1, X[:, 1].max() + 1
xx, yy = np.meshgrid(np.arange(x_min, x_max, plot_step),
                     np.arange(y_min, y_max, plot_step))

Z = Boost_rand.predict(np.c_[xx.ravel(), yy.ravel()])
Z = Z.reshape(xx.shape)
cs = plt.contourf(xx, yy, Z, cmap= plt.cm.RdYlGn)
plt.axis("tight")

# Plot the training points
for i, n, c in zip(range(2), class_names, plot_colors):
    idx = np.where(y == i)
    plt.scatter(X[idx, 0], X[idx, 1],
                c= c, cmap=plt.cm.RdYlGn,
                s=40, edgecolor='k',
                label="Class %s" % n)
plt.xlim(x_min, x_max)
plt.ylim(y_min, y_max)
plt.legend(loc='upper right')
plt.xlabel('x')
plt.ylabel('y')
plt.title('Decision Boundary')

# Plot the two-class decision scores
twoclass_output = Boost_rand.decision_function(X)
plot_range = (twoclass_output.min(), twoclass_output.max())
plt.subplot(122)
for i, n, c in zip(range(2), class_names, plot_colors):
    plt.hist(twoclass_output[y == i],
             bins=10,
             range=plot_range,
             facecolor=c,
             label='Class %s' % n,
             alpha=0.7,
             edgecolor='k')
plt.yscale('log')
plt.legend(loc='upper right')
plt.ylabel('Samples')
plt.xlabel('Score')
plt.title('Decision Scores')

plt.tight_layout()
plt.subplots_adjust(wspace=0.2)
plt.show()

In X ci sono i valori di CO(GT) in Y quelli della NOx(GT)

Il decision boundary per questi due atrtibuti si vede abbastanza bene anche se le performance non sono il massimo infatti con ADABoost su randomForest si arriva a accuracy di 0.81 ma non oltre

## **Bagging**

Faccio bagging su random Forest

In [72]:
from sklearn.ensemble import BaggingClassifier

In [73]:
param_grid = {"n_estimators": [1, 5, 10, 50, 100],
              "max_samples": [1, 10, 50, 100,500,1000],
              "max_features":[1,2,3,4,5,6,7,8,9,10,11]
             }

# run grid search
grid = GridSearchCV(BaggingClassifier(RandomForestClassifier(bootstrap=True, ccp_alpha=0.0, class_weight=None,
                       criterion='gini', max_depth=8, max_features='auto',
                       max_leaf_nodes=None, max_samples=None,
                       min_impurity_decrease=0.0, min_impurity_split=None,
                       min_samples_leaf=2, min_samples_split=2,
                       min_weight_fraction_leaf=0.0, n_estimators=10,
                       n_jobs=None, oob_score=False, random_state=None,
                       verbose=0, warm_start=False)),cv = 5, param_grid=param_grid, scoring = 'accuracy')
grid.fit(X_train, y_train)

GridSearchCV(cv=5, error_score=nan,
             estimator=BaggingClassifier(base_estimator=RandomForestClassifier(bootstrap=True,
                                                                               ccp_alpha=0.0,
                                                                               class_weight=None,
                                                                               criterion='gini',
                                                                               max_depth=8,
                                                                               max_features='auto',
                                                                               max_leaf_nodes=None,
                                                                               max_samples=None,
                                                                               min_impurity_decrease=0.0,
                                                                               min_im

In [74]:
Bagg= grid.best_estimator_
Bagg

BaggingClassifier(base_estimator=RandomForestClassifier(bootstrap=True,
                                                        ccp_alpha=0.0,
                                                        class_weight=None,
                                                        criterion='gini',
                                                        max_depth=8,
                                                        max_features='auto',
                                                        max_leaf_nodes=None,
                                                        max_samples=None,
                                                        min_impurity_decrease=0.0,
                                                        min_impurity_split=None,
                                                        min_samples_leaf=2,
                                                        min_samples_split=2,
                                                        min_weight_fraction_leaf=0.0,
        

Questi sopra i parametri del miglior bagging su random forest , elenca qua quelli più "significativi":
- class_weight=None,
- criterion='gini',
- max_depth=8,
- max_features='auto',
- max_leaf_nodes=None,
- min_samples_leaf=2,
- min_samples_split=2,
- n_estimators=10,



In [75]:
Bagg.fit(X_train, y_train)

y_pred = Bagg.predict(X_test)

print('Accuracy %s' % accuracy_score(y_test, y_pred))
print('F1-score %s' % f1_score(y_test, y_pred, average=None))
print(classification_report(y_test, y_pred))

Accuracy 0.7542735042735043
F1-score [0.84977139 0.3255132 ]
              precision    recall  f1-score   support

           0       0.75      0.98      0.85      1332
           1       0.78      0.21      0.33       540

    accuracy                           0.75      1872
   macro avg       0.77      0.59      0.59      1872
weighted avg       0.76      0.75      0.70      1872



Con Bagging su Random Forest abbiamo avuto un accuracy di 0.75



**In generale tra RandomForest, AdaBoost e Bagging il meglio è stato AdaBoost su RandomForest con performance di accuracy 0.82**